{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d147ce83",
   "metadata": {},
   "outputs": [],
   "source": [
    "''' 장비 준비 '''\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torchvision import transforms, datasets\n",
    "import random\n",
    "from torchsummary import summary\n",
    "from sklearn.model_selection import train_test_split\n",
    "from torch.utils.data import Subset, DataLoader\n",
    "import torchvision.models as models\n",
    "from efficientnet_pytorch import EfficientNet\n",
    "\n",
    "PATH = './weight/'\n",
    "DEVICE = torch.device(\"cuda\")\n",
    "\n",
    "model = models.resnet18()\n",
    "optimizer = torch.optim.Adam(model.parameters(), lr=0.002)\n",
    "\n",
    "model = torch.load(PATH + 'model.pt')  # 전체 모델을 통째로 불러옴, 클래스 선언 필수\n",
    "model.to(DEVICE)\n",
    "\n",
    "def evaluate(model, test_loader):\n",
    "    model.eval()\n",
    "    num_of_mini_batch = len(test_loader)\n",
    "    #print(num_of_mini_batch)\n",
    "    prediction_list = []\n",
    "    no_count = 0\n",
    "    yes_count = 0\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for image, label in test_loader :\n",
    "            image = image.to(DEVICE)\n",
    "            #label = label - 1 # GPU 환경에서만 적용\n",
    "            label = label.to(DEVICE)\n",
    "            output = model(image)\n",
    "            prediction = output.max(1, keepdim = True)[1]\n",
    "            if prediction == 0:\n",
    "                no_count +=1\n",
    "            else:\n",
    "                yes_count+=1\n",
    "                \n",
    "            prediction_list.append(prediction)    \n",
    "    return prediction_list, no_count, yes_count\n",
    "\n",
    "#seed = 777\n",
    "#BATCH_SIZE = 32\n",
    "\n",
    "''' 데이터셋 준비 '''\n",
    "path = './dataset' # 불러올 데이터셋 경로 를 수정하여야 함.\n",
    "\n",
    "# 폴더 안의 이미지 데이터 불러오기\n",
    "dataset = datasets.ImageFolder(root = path,\n",
    "                              transform = transforms.Compose([\n",
    "                                  transforms.Resize((224,224)),\n",
    "                                  transforms.RandomHorizontalFlip(p=0.3),\n",
    "                                  transforms.RandomGrayscale(p=0.1),\n",
    "                                  transforms.ToTensor(),\n",
    "                                  transforms.Normalize([0.4, 0.4, 0.4], [0.2, 0.2, 0.2])\n",
    "                              ])) \n",
    "\n",
    "# train/test data 분리. 사이킷런 train_test_split과 torch.utils.data의 Subset 활용\n",
    "test_idx = list(range(len(dataset)))\n",
    "test_data = Subset(dataset, test_idx)\n",
    "\n",
    "# 학습/평가용 데이터 생성 완료\n",
    "test_loader = DataLoader(test_data, batch_size = 1, shuffle = False)\n",
    "\n",
    "prediction_list, no_count, yes_count = evaluate(model, test_loader)\n",
    "print(no_count, yes_count)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
